### ISSUE TITLE
Fixed background images

### ISSUE THREAD

**Issue by Acovendesigns** [guidobouman/jquery-panelsnap#122]
I'm trying to set background images to fixed with panel snap and am not sure if it's setup to handle this can you confirm if this is possible with the plugin?

Here's the effect I'm looking to achieve with panel snap integrated.
[codepen](https://codepen.io/alcoven/pen/xPMLyx)

Much appreciated!
-Alex

**Comment by guidobouman** [comment]
You could always CSS:

```css
.panel {
  background-attachment: fixed;
}
```

Or explore some newer property:
```css
.background {
  position: sticky;
}
```
